### ISSUE TITLE
Justin Searl's talk is listed twice

### ISSUE THREAD

**Issue by mateodelnorte** [EmpireJS/2017.empirejs.org#17]

**Comment by mateodelnorte** [comment]
Guessing someone else's got left off

**Comment by joesepi** [comment]
I believe this is just that there is a break, so the workshops are both sorta listed twice, but the heading of the sections says "(Workshops Continue)". Perhaps they should each say "(continued)" after their title after the break.

**Comment by afeld** [comment]
I'm removing the repeated listing of the workshops in #16.
