### ISSUE TITLE
hotel reservation info. 

### ISSUE THREAD

**Issue by LopezCatherine** [EmpireJS/2017.empirejs.org#22]
The Empire Group rates are now available online for [Hotel Wales](https://www.hotelwalesnyc.com/) at 1295 Madison Avenue (Between 92ND & 93RD), New York, NY 10128. 

You have the option of booking reservations with the link below or calling our off site reservations at 1.866.925.3746.
Group Code – 228450
 
HTML Link: https://gc.synxis.com/rez.aspx?Hotel=15229&Chain=6158&arrive=10/10/2017&depart=10/16/2017&adult=1&child=0&group=228450

**Comment by afeld** [comment]
Closed by #25.
